# Generated by Django 4.1 on 2023-05-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_no", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "ad_article", "managed": False,},
        ),
        migrations.CreateModel(
            name="AdGene",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("pmid", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("journal", models.CharField(blank=True, max_length=255, null=True)),
                ("evidence", models.CharField(blank=True, max_length=255, null=True)),
                ("species", models.CharField(blank=True, max_length=255, null=True)),
                ("tissue", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sample_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"db_table": "ad_gene", "managed": False,},
        ),
    ]
