# Generated by Django 4.1 on 2023-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_psw", models.CharField(max_length=20)),
                ("user_grade", models.CharField(blank=True, max_length=20, null=True)),
                ("user_no", models.CharField(db_column="user_No", max_length=20)),
            ],
            options={"db_table": "user", "managed": False,},
        ),
    ]
