# Generated by Django 5.0.3 on 2024-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sheet1",
            fields=[
                (
                    "mature_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("mature_seq", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mature_seed_seq",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mature_seed_same",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mature_chrom",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mature_pre_mir",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mature_conf",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mature_pre_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "sheet1",
                "managed": False,
            },
        ),
    ]
